version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile 
    image: baotongxuan/food-delivery:nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

  delivery:
    build:
      context: ./delivery
    image: baotongxuan/food-delivery:delivery
    healthcheck:
      test: ["CMD", "curl", "-f", "http://delivery:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  order:
    build:
      context: ./order
    image: baotongxuan/food-delivery:order
    healthcheck:
      test: ["CMD", "curl", "-f", "http://order:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  restaurant:
    build:
      context: ./restaurant
    image: baotongxuan/food-delivery:restaurant
    healthcheck:
      test: ["CMD", "curl", "-f", "http://restaurant:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  user:
    build:
      context: ./user
    image: baotongxuan/food-delivery:user
    healthcheck:
      test: ["CMD", "curl", "-f", "http://user:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  simulator:
    build:
      context: ./simulator
    image: baotongxuan/food-delivery:simulator
    healthcheck:
      test: ["CMD", "curl", "-f", "http://simulator:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 5

