version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile 
    depends_on:
      delivery:
        condition: service_healthy
      restaurant:
        condition: service_healthy
      order:
        condition: service_healthy
      user:
        condition: service_healthy
      simulator:
        condition: service_healthy
    ports:
      - "80:80"

  delivery:
    build: 
      context: ./delivery
      target: development
    volumes:
      - ./delivery:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://delivery:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  order:
    build: 
      context: ./order
      target: development
    volumes:
      - ./order:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://order:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  restaurant:
    build: 
      context: ./restaurant
      target: development
    volumes:
      - ./restaurant:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://restaurant:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  user:
    build: 
      context: ./user
      target: development
    volumes:
      - ./user:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://user:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  simulator:
    build: 
      context: ./simulator
      target: development
    volumes:
      - ./simulator:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://simulator:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 5
